/* =============================================================================
   01_demo_objects.sql — database, warehouses, schemas
   -----------------------------------------------------------------------------
   SYSADMIN creates, then hands ownership to OF_SHAREPOINT_ADMIN.
   ============================================================================= */

USE ROLE SYSADMIN;

/* --- Warehouse (SMALL — AI_EXTRACT needs at least SMALL) --- */
CREATE WAREHOUSE IF NOT EXISTS OF_SHAREPOINT_WH
    WAREHOUSE_SIZE      = 'SMALL'
    AUTO_SUSPEND        = 60
    AUTO_RESUME         = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'SharePoint demo — queries, connector, and AI_EXTRACT';

/* --- Database (Iceberg-enabled) --- */
CREATE DATABASE IF NOT EXISTS OF_SHAREPOINT
    COMMENT = 'SharePoint Openflow store ops demo';

/* --- Hand ownership --- */
GRANT OWNERSHIP ON DATABASE  OF_SHAREPOINT    TO ROLE OF_SHAREPOINT_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE OF_SHAREPOINT_WH TO ROLE OF_SHAREPOINT_ADMIN COPY CURRENT GRANTS;

/* --- Iceberg settings (as owner) --- */
USE ROLE OF_SHAREPOINT_ADMIN;

ALTER DATABASE OF_SHAREPOINT SET
    EXTERNAL_VOLUME              = 'SNOWFLAKE_MANAGED'
    STORAGE_SERIALIZATION_POLICY = COMPATIBLE
    ICEBERG_VERSION_DEFAULT      = 3;

USE DATABASE OF_SHAREPOINT;

/* --- Schemas --- */
CREATE SCHEMA IF NOT EXISTS DOCS
    COMMENT = 'SharePoint documents, ACLs, AI extraction, structured output';

CREATE SCHEMA IF NOT EXISTS OPENFLOW
    COMMENT = 'Gen 2 Openflow deployment + runtime objects';

DROP SCHEMA IF EXISTS PUBLIC;

/* --- Grant runtime role access --- */
GRANT USAGE ON DATABASE OF_SHAREPOINT TO ROLE OF_SHAREPOINT_RUNTIME_ROLE;

GRANT USAGE ON SCHEMA OF_SHAREPOINT.DOCS TO ROLE OF_SHAREPOINT_RUNTIME_ROLE;
GRANT CREATE TABLE, CREATE DYNAMIC TABLE, CREATE STAGE, CREATE SEQUENCE,
      CREATE CORTEX SEARCH SERVICE
    ON SCHEMA OF_SHAREPOINT.DOCS TO ROLE OF_SHAREPOINT_RUNTIME_ROLE;

GRANT USAGE, OPERATE ON WAREHOUSE OF_SHAREPOINT_WH
    TO ROLE OF_SHAREPOINT_RUNTIME_ROLE;

GRANT USAGE ON SCHEMA OF_SHAREPOINT.OPENFLOW TO ROLE OF_SHAREPOINT_RUNTIME_ROLE;

/* --- FUTURE TABLES so we can SELECT on connector-created objects --- */
USE ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OF_SHAREPOINT.DOCS
    TO ROLE OF_SHAREPOINT_ADMIN;
USE ROLE OF_SHAREPOINT_ADMIN;

/* --- Verify --- */
SHOW PARAMETERS LIKE 'EXTERNAL_VOLUME'              IN DATABASE OF_SHAREPOINT;
SHOW PARAMETERS LIKE 'STORAGE_SERIALIZATION_POLICY' IN DATABASE OF_SHAREPOINT;
SHOW PARAMETERS LIKE 'ICEBERG_VERSION_DEFAULT'      IN DATABASE OF_SHAREPOINT;
SHOW SCHEMAS IN DATABASE OF_SHAREPOINT;
SHOW WAREHOUSES LIKE 'OF_SHAREPOINT%';
