/* =============================================================================
   05_reset.sql — reset the AI layer, keep connector data
   -----------------------------------------------------------------------------
   Run as OF_SHAREPOINT_ADMIN. Safe to run repeatedly.

   DROPS: DOC_CLASSIFY_RAW, DOC_EXTRACT_RAW, all dynamic tables, all tasks,
          STORE_OPS_SEARCH
   KEEPS: DOCS_CHUNKS, DOCUMENTS stage, FILE_HASHES, ACL tables,
          CORTEX_SEARCH_SERVICE (connector-managed) — no re-ingest needed

   After this, re-run 04_ai_pipeline.sql.
   ============================================================================= */

USE ROLE OF_SHAREPOINT_ADMIN;
USE DATABASE OF_SHAREPOINT;
USE SCHEMA DOCS;
USE WAREHOUSE OF_SHAREPOINT_WH;

/* Reassert grants on connector-owned objects */
USE ROLE ACCOUNTADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA OF_SHAREPOINT.DOCS TO ROLE OF_SHAREPOINT_ADMIN;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA OF_SHAREPOINT.DOCS TO ROLE OF_SHAREPOINT_ADMIN;
GRANT READ ON STAGE OF_SHAREPOINT.DOCS.DOCUMENTS TO ROLE OF_SHAREPOINT_ADMIN;
USE ROLE OF_SHAREPOINT_ADMIN;

/* Sanity check */
SELECT COUNT(DISTINCT METADATA:id::STRING) AS DOCS_INGESTED FROM DOCS_CHUNKS;

/* Suspend root task (children auto-suspend) */
ALTER TASK IF EXISTS TASK_CLASSIFY_DOCS SUSPEND;

/* Drop children first */
DROP TASK IF EXISTS TASK_EXTRACT_INSPECTIONS;
DROP TASK IF EXISTS TASK_EXTRACT_MAINTENANCE;
DROP TASK IF EXISTS TASK_EXTRACT_INCIDENTS;
DROP TASK IF EXISTS TASK_EXTRACT_PLANOGRAMS;
DROP TASK IF EXISTS TASK_CLASSIFY_DOCS;

/* Dynamic tables */
DROP DYNAMIC TABLE IF EXISTS INSPECTION_FINDINGS;
DROP DYNAMIC TABLE IF EXISTS MAINTENANCE_ORDERS;
DROP DYNAMIC TABLE IF EXISTS INCIDENT_REPORTS;
DROP DYNAMIC TABLE IF EXISTS PLANOGRAM_FINDINGS;

/* Structured findings search (keep connector's CORTEX_SEARCH_SERVICE) */
DROP CORTEX SEARCH SERVICE IF EXISTS STORE_OPS_SEARCH;

/* Raw tables */
DROP ICEBERG TABLE IF EXISTS DOC_EXTRACT_RAW;
DROP ICEBERG TABLE IF EXISTS DOC_CLASSIFY_RAW;

/* Agent + semantic view */
DROP CORTEX AGENT IF EXISTS STORE_OPS_AGENT;
DROP SEMANTIC VIEW IF EXISTS STORE_OPS_ANALYTICS;
