/* =============================================================================
   99_teardown.sql — drop everything, in dependency order
   -----------------------------------------------------------------------------
   DESTRUCTIVE. This deletes the demo database and all Iceberg data.

   STEP 0 (MANUAL): Stop and delete the SharePoint connector in Openflow UI.
   ============================================================================= */

USE ROLE OPENFLOW_DEMO_ADMIN;
USE DATABASE OPENFLOW_DEMO;

/* Stop the moving parts */
ALTER TASK IF EXISTS SHAREPOINT_DOCS.TASK_CLASSIFY_AND_EXTRACT SUSPEND;

/* Our objects */
DROP DYNAMIC TABLE IF EXISTS SHAREPOINT_DOCS.INSPECTION_FINDINGS;
DROP DYNAMIC TABLE IF EXISTS SHAREPOINT_DOCS.MAINTENANCE_ORDERS;
DROP DYNAMIC TABLE IF EXISTS SHAREPOINT_DOCS.INCIDENT_REPORTS;
DROP DYNAMIC TABLE IF EXISTS SHAREPOINT_DOCS.PLANOGRAM_FINDINGS;
DROP TASK          IF EXISTS SHAREPOINT_DOCS.TASK_CLASSIFY_AND_EXTRACT;
DROP ICEBERG TABLE IF EXISTS SHAREPOINT_DOCS.DOC_EXTRACT_RAW;

/* Gen 2 Openflow: runtime first, then deployment */
USE ROLE OPENFLOW_ADMIN;
DROP OPENFLOW RUNTIME IF EXISTS OPENFLOW_DEMO.OPENFLOW.OPENFLOW_DEMO_RUNTIME;
DROP OPENFLOW DEPLOYMENT IF EXISTS OPENFLOW_DEMO_DEPLOYMENT;

/* EAIs */
USE ROLE ACCOUNTADMIN;
DROP INTEGRATION IF EXISTS EAI_OPENFLOW_SHAREPOINT;

/* The database (takes schemas, network rules, etc. with it) */
DROP DATABASE IF EXISTS OPENFLOW_DEMO;

/* Integrations */
DROP INTEGRATION IF EXISTS NI_EMAIL_DEMO_ALERTS;

/* Warehouses */
DROP WAREHOUSE IF EXISTS OPENFLOW_DEMO_WH;
DROP WAREHOUSE IF EXISTS OPENFLOW_DEMO_INGEST_WH;

/* Roles */
USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS OPENFLOW_DEMO_ADMIN;
DROP ROLE IF EXISTS OPENFLOW_RUNTIME_ROLE_OPENFLOW_DEMO_RUNTIME;
-- DROP ROLE IF EXISTS OPENFLOW_ADMIN;  -- keep if other deployments exist

/* Verify */
USE ROLE ACCOUNTADMIN;
SHOW DATABASES  LIKE 'OPENFLOW_DEMO';
SHOW WAREHOUSES LIKE 'OPENFLOW_DEMO%';
SHOW ROLES      LIKE 'OPENFLOW_DEMO%';
