/* =============================================================================
   99_teardown.sql — drop everything
   -----------------------------------------------------------------------------
   DESTRUCTIVE. Run each statement individually — some may no-op if objects
   are already gone. Every statement uses IF EXISTS or is wrapped to tolerate
   missing objects.

   STEP 0 (MANUAL): Stop and delete the SharePoint connector in Openflow UI.
   ============================================================================= */

USE ROLE OF_SHAREPOINT_ADMIN;
USE DATABASE OF_SHAREPOINT;

/* --- Tasks (suspend root, drop children first) --- */
ALTER TASK IF EXISTS DOCS.TASK_CLASSIFY_DOCS SUSPEND;
DROP TASK IF EXISTS DOCS.TASK_EXTRACT_INSPECTIONS;
DROP TASK IF EXISTS DOCS.TASK_EXTRACT_MAINTENANCE;
DROP TASK IF EXISTS DOCS.TASK_EXTRACT_INCIDENTS;
DROP TASK IF EXISTS DOCS.TASK_EXTRACT_PLANOGRAMS;
DROP TASK IF EXISTS DOCS.TASK_CLASSIFY_DOCS;

/* --- Dynamic tables --- */
DROP DYNAMIC TABLE IF EXISTS DOCS.INSPECTION_FINDINGS;
DROP DYNAMIC TABLE IF EXISTS DOCS.MAINTENANCE_ORDERS;
DROP DYNAMIC TABLE IF EXISTS DOCS.INCIDENT_REPORTS;
DROP DYNAMIC TABLE IF EXISTS DOCS.PLANOGRAM_FINDINGS;

/* --- Raw tables --- */
DROP ICEBERG TABLE IF EXISTS DOCS.DOC_EXTRACT_RAW;
DROP ICEBERG TABLE IF EXISTS DOCS.DOC_CLASSIFY_RAW;

/* --- Openflow runtime: suspend → terminate → drop ---
   Run these one at a time. Skip any that error with "does not exist". */
ALTER OPENFLOW RUNTIME OF_SHAREPOINT.OPENFLOW.OF_SHAREPOINT_RUNTIME SUSPEND;
SELECT SYSTEM$WAIT_FOR_STABLE_OPENFLOW_RUNTIMES(300, 'OF_SHAREPOINT.OPENFLOW.OF_SHAREPOINT_RUNTIME');

ALTER OPENFLOW RUNTIME OF_SHAREPOINT.OPENFLOW.OF_SHAREPOINT_RUNTIME TERMINATE;
SELECT SYSTEM$WAIT_FOR_STABLE_OPENFLOW_RUNTIMES(300, 'OF_SHAREPOINT.OPENFLOW.OF_SHAREPOINT_RUNTIME');

DROP OPENFLOW RUNTIME IF EXISTS OF_SHAREPOINT.OPENFLOW.OF_SHAREPOINT_RUNTIME;

/* --- Openflow deployment: same lifecycle --- */
ALTER OPENFLOW DEPLOYMENT OF_SHAREPOINT_DEPLOYMENT SUSPEND;
SELECT SYSTEM$WAIT_FOR_STABLE_OPENFLOW_DEPLOYMENTS(300, 'OF_SHAREPOINT_DEPLOYMENT');

ALTER OPENFLOW DEPLOYMENT OF_SHAREPOINT_DEPLOYMENT TERMINATE;
SELECT SYSTEM$WAIT_FOR_STABLE_OPENFLOW_DEPLOYMENTS(300, 'OF_SHAREPOINT_DEPLOYMENT');

DROP OPENFLOW DEPLOYMENT IF EXISTS OF_SHAREPOINT_DEPLOYMENT;

/* --- Integrations (ACCOUNTADMIN) --- */
USE ROLE ACCOUNTADMIN;
DROP INTEGRATION IF EXISTS OF_SHAREPOINT_EAI;

/* --- Database (takes schemas, network rules, stages with it) --- */
DROP DATABASE IF EXISTS OF_SHAREPOINT;

/* --- Warehouses --- */
DROP WAREHOUSE IF EXISTS OF_SHAREPOINT_WH;
DROP WAREHOUSE IF EXISTS OF_SHAREPOINT_INGEST_WH;

/* --- Roles --- */
USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS OF_SHAREPOINT_ADMIN;
DROP ROLE IF EXISTS OF_SHAREPOINT_RUNTIME_ROLE;

/* --- Verify nothing remains --- */
USE ROLE ACCOUNTADMIN;
SHOW DATABASES  LIKE 'OF_SHAREPOINT';
SHOW WAREHOUSES LIKE 'OF_SHAREPOINT%';
SHOW ROLES      LIKE 'OF_SHAREPOINT%';
